export const FETCH_PROJECT_START = 'FETCH_PROJECT_START';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAIL = 'FETCH_PROJECT_FAIL';

export const FETCH_ALL_PROJECT_START = 'FETCH_ALL_PROJECT_START';
export const FETCH_ALL_PROJECT_SUCCESS = 'FETCH_ALL_PROJECT_SUCCESS';
export const FETCH_ALL_PROJECT_FAIL = 'FETCH_ALL_PROJECT_FAIL';

export const DELETE_PROJECT_START = 'DELETE_PROJECT_START';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';



// ------------------

export const FETCH_PROJECTTASK_START  = 'FETCH_PROJECTTASK_START';
export const FETCH_PROJECTTASK_SUCCESS  = 'FETCH_PROJECTTASK_SUCCESS';
export const FETCH_PROJECTTASK_FAIL  = 'FETCH_PROJECTTASK_FAIL';


export const FETCH_ALL_BACKLOGS_START  = 'FETCH_ALL_BACKLOGS_START';
export const FETCH_ALL_BACKLOGS_SUCCESS = 'FETCH_ALL_BACKLOGS_SUCCESS';
export const FETCH_ALL_BACKLOGS_FAIL = 'FETCH_ALL_BACKLOGS_FAIL';

export const DELETE_PROJECT_TASK_START  = 'DELETE_PROJECT_TASK_START';
export const DELETE_PROJECT_TASK_SUCCESS = 'DELETE_PROJECT_TASK_SUCCESS';
export const DELETE_PROJECT_TASK_FAIL = 'DELETE_PROJECT_TASK_FAIL';